import Head from 'next/head';
import { useState } from 'react';
import { useSession } from 'next-auth/react';
import { signOut } from 'next-auth/react';
import Info from '../components/Info';
import Review from '../components/Review';
import styles from '../styles/Home.module.css';
import { useRouter } from 'next/router';

const Dashboard = () => {
  const router = useRouter();
  const session = useSession();
  const [InfoButtonClicked, setInfoButtonClicked] = useState(true);
  const [reviewButtonClicked, setReviewButtonClicked] = useState(false);

  if (session.status === 'unauthenticated') {
    router.push('/');
    return null;
  }
  const handleLogout = async () => {
    localStorage.removeItem('loginUserId');
    await signOut('google').then(() => {
      router.push('/login');
    });
  };

  return (
    <div className="container-fluid">
      <div className="row">
        <div className="col-lg-2 col-md-3 col-sm-4 bg-light sidebar">
          <div id="homeContainer" className="d-flex flex-column p-3">
            <button
              className={`btn btn-light mb-3 ${
                InfoButtonClicked ? 'active' : ''
              }`}
              onClick={() => {
                setInfoButtonClicked(true);
                setReviewButtonClicked(false);
              }}
            >
              Info
            </button>
            <button
              className={`btn btn-light ${reviewButtonClicked ? 'active' : ''}`}
              onClick={() => {
                setReviewButtonClicked(true);
                setInfoButtonClicked(false);
              }}
            >
              Reviews
            </button>
          </div>
        </div>

        <div className="col-lg-10 col-md-9 col-sm-8">
          <div className={styles.container}>
            <Head>
              <title>Create Next App</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className="d-flex justify-content-between align-items-center p-3">
              <p className="mb-0">
                Welcome {session?.data?.user?.name} {}
              </p>
              <button className="btn btn-primary" onClick={handleLogout}>
                Logout
              </button>
            </div>

            <div className="p-3">
              {InfoButtonClicked && <Info />}
              {reviewButtonClicked && <Review />}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Dashboard;
